CoreNLPServerAddress = "CoreNLPServerAddress"
HistoryFilePath = "HistoryFilePath"
SearchAddress = "SearchAddress"
IsStubMode = "IsStubMode"
InterfaceTypeKey = "InterfaceType"
LogLevelKey = "LogLevel"
StartMessageKey = "StartMessage"
TokenKey = "Token"